
require('plugin_configs.kanawaga')
require('plugin_configs.lualine')
require('plugin_configs.bufferline')
require('plugin_configs.telescope')
require('plugin_configs.nvim-tree')
require('plugin_configs.treesitter')
require('plugin_configs.zen-mode')
require('plugin_configs.aerial')
require('plugin_configs.key-analyzer')
require('plugin_configs.indent-blankline')
require('plugin_configs.virt-column')
require('plugin_configs.snacks')
require('plugin_configs.nvim-scrollbar')
