enable_audio_bell no
hide_window_decorations yes
#allow_remote_control yes
font_size 12.0

#background_opacity .82
background_image_layout centered
background_tint 0.80

#background_image /home/jvalcher/Pictures/wallpapers/aqua_sky_mountainside_moss.png
#background_image /home/jvalcher/Pictures/wallpapers/black_waves.jpg
#background_image /home/jvalcher/Pictures/wallpapers/blue_brick.png
#background_image /home/jvalcher/Pictures/wallpapers/dark_blue_black_gradient.png
#background_image /home/jvalcher/Pictures/wallpapers/dark_blue_radiation.jpg
#background_image /home/jvalcher/Pictures/wallpapers/dark_gray_texture_clock.png
background_image /home/jvalcher/Pictures/wallpapers/dark_red_blue_mountain_river.png
#background_image /home/jvalcher/Pictures/wallpapers/dark_teal_black_texture_gradient.jpg
#background_image /home/jvalcher/Pictures/wallpapers/dark_teal_tan_black_sand_dune.png
#background_image /home/jvalcher/Pictures/wallpapers/space_cloud_stars.png
#background_image /home/jvalcher/Pictures/wallpapers/space_green_planet.png
#background_image /home/jvalcher/Pictures/wallpapers/space_mist_planet.png
#background_image /home/jvalcher/Pictures/wallpapers/teal_pink_black_random_shapes.jpg
#background_image /home/jvalcher/Pictures/wallpapers/dark_blue_black_gradient.png
